services:
  app:
    build:
      dockerfile: Dockerfile
      target: dev
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      - db
    volumes:
      - ./:/app/

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    env_file:
      - .env
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d